# The Site Configuration

description: SiZK's competitive programming library
highlightjs-style: tokyo-night-dark
filename-index: true

url: "https://p-sizk.github.io"
baseurl: "/competitive-programming-library"

remote_theme: vaibhavvikas/jekyll-theme-minimalistic

favicon: true
color-scheme: dark

platforms:
  - name: P-SiZK
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/P-SiZK
  - name: P_SiZK
    icon: <i class="fa-brands fa-x-twitter"></i>
    link: https://x.com/P_SiZK
